mediaserver: Update mediaserver HALv1 dependencies for O
 * Add libcameraservice shared library dependency
 * Add new android.hardware.camera.common@1.0 and
    android.hardware.camera.provider@2.4 shared
    libraries and exported headers HAL dependencies

 * Add libarect static library dependency

 * When TARGET_HAS_LEGACY_CAMERA_HAL1 is set, the mediaserver
    includes CameraService.h but exported headers are missing

 * Error upon build due to missing libcameraservice linkage:
    fatal error: 'android/hardware/BnCameraService.h' file not found

Change-Id: Ib6bb8a4e9ef18606c64e2dff13504d2eeaac13b1
Signed-off-by: Adrian DC <radian.dc@gmail.com>